### ISSUE TITLE
section 6.6 too much focus on RDF statistics

### ISSUE THREAD

**Issue by mdmiller53** [indiedotkim/HCLSDatasetDescriptions#101]
section 6.6 has too much a focus on RDF statistics, it would be good to ideally have examples for databases and spreadsheets

**Comment by mscottm** [comment]
Michael - could you provide such examples by next week?

**Comment by mdmiller53** [comment]
hi scott and all,



i've thought a bit about this, but not to much of depth.  i'm currently
taking an edX course on the challenges of big dat
<https://mitprofessionalx.edx.org/courses/MITProfessionalX/6.BD_2X/3T2015/about>a
that is taking up a lot of my not so free time (great course!).  missed the
call this morning due to the holiday but perhaps next monday we can briefly
talk about this?  i'm taking a vacation this next weekend but i think  i
should be able to come up with something by early march.



cheers,

michael



Michael Miller

Software Engineer

Institute for Systems Biology





*From:* mscottm [mailto:notifications@github.com]
*Sent:* Monday, February 16, 2015 8:47 AM
*To:* joejimbo/HCLSDatasetDescriptions
*Cc:* mdmiller53
*Subject:* Re: [HCLSDatasetDescriptions] section 6.6 too much focus on RDF
statistics (#101)



Michael - could you provide such examples by next week?

—
Reply to this email directly or view it on GitHub
<https://github.com/joejimbo/HCLSDatasetDescriptions/issues/101#issuecomment-74537416>
.
