### ISSUE TITLE
Move sio:is-data-item-in

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#103]
I think it is confusing to have ```sio:is-data-item-in``` as part of the table of metadata properties in Section 5. All of the other properties have the metadata as the subject. This property has the metadata as the object. We should move it to its own table at the end and write up about it in the use of the metadata descriptions section.

**Comment by micheldumontier** [comment]
ok, but sio:has-data-item could apply?

**Comment by micheldumontier** [comment]
see commit f6331a2d9d9d0ad16fbd7fab557f3cf4bad900c7
