### ISSUE TITLE
sio:is-data-item-in

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#104]
Can this property be used for non-RDF datasets?
I believe from the ```sio``` description that it can be, but does this make sense. How would it be used? We will need to describe its usage in Section 7.

**Comment by micheldumontier** [comment]
this would make sense if there was at least a URI for the data item.

**Comment by micheldumontier** [comment]
I think this is related to the broadening the note to beyond RDF dataset descriptions. I'd rather not include this for publication.
