### ISSUE TITLE
Enhanced statistics table entries

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#105]
Patterns in the table in Section 5 for enhanced statistics do not include terms from ```void-ext```, is this correct?

**Comment by micheldumontier** [comment]
void-ext applies to a void:propertyPartition ... so it wouldn't directly modify a dataset description.

**Comment by mscottm** [comment]
Agree that the partitions added by void:ext would only describe subsets of a dataset.

**Comment by AlasdairGray** [comment]
Currently the guidance notes on the statistics and the table do not tally up directly. They go astray at Section 6.6.1.6.
The table also doesn't distinguish between core statistics and enhanced statistics. There is an ```sd:namedGraph``` in the table which does not seem to be in the guidance notes.
Then there is the third column of the table which is what this thread needs to address

**Comment by micheldumontier** [comment]
I've updated the page see fdffe34abe311f814e12248ee638aedf071a2a59

**Comment by AlasdairGray** [comment]
To ease validation, we won't check the shape of the statistics expressions
