### ISSUE TITLE
linking to arbitrary resources

### ISSUE THREAD

**Issue by micheldumontier** [indiedotkim/HCLSDatasetDescriptions#106]
At the RDF metadata and semantics workshop. Question came up about linking to arbitrary resources that are relevant to the resource. Might suggest we add rdfs:seeAlso link to any IRI that provides information about the dataset/version/distribution

**Comment by AlasdairGray** [comment]
This sounds sensible. I assume it would be a MAY property

**Comment by mscottm** [comment]
Agree with MAY property.

**Comment by micheldumontier** [comment]
yes, MAY
