### ISSUE TITLE
agent identifiers vs web pages

### ISSUE THREAD

**Issue by micheldumontier** [indiedotkim/HCLSDatasetDescriptions#107]
Phil Archer raised the issue as to why we were using web page URIs for agents.
e.g.
:chembl17
    dct:creator <https://www.ebi.ac.uk/chembl/> .

should perhaps be:

:chembl17
    dct:creator [foaf:page <https://www.ebi.ac.uk/chembl/>] .

similarly,
:chembl
    dct:publisher [foaf:homepage <http://www.ebi.ac.uk> ].

**Comment by AlasdairGray** [comment]
This is getting into the [HTTPRange-14](http://en.wikipedia.org/wiki/HTTPRange-14) debate and depends upon what you interpret the URI to mean.

Here we are using the URIs to mean the organisation, not the page served by a HTTP request.

The same issue arises for all the creator/author/curator predicates which should refer to a ```foaf:Person``` not to a webpage about the person. For example, what is the type of an ORCID URI, e.g. http://orcid.org/0000-0002-5711-4872?

**Comment by mscottm** [comment]
Just to add to Alasdair's comments: This also points to the general lack of official URIs for people and organizations. I suppose that is why Phil suggested the foaf predicates - to make clear when we don't actually have the URI for the agent or institution.

**Comment by AlasdairGray** [comment]
Resolution: update guidance text to correctly address this issue 

Working example would need to correctly use this.

**Comment by micheldumontier** [comment]
EBI does not have URIs for the organization, but they do have them for the dataset and version

e.g. http://rdf.ebi.ac.uk/dataset/chembl and http://rdf.ebi.ac.uk/dataset/chembl/20.0 

we should update the document accordingly.

**Comment by AlasdairGray** [comment]
This has been fixed in the example and the guidance notes updated
