### ISSUE TITLE
references

### ISSUE THREAD

**Issue by micheldumontier** [indiedotkim/HCLSDatasetDescriptions#109]
Might suggest we go with dct:references instead of cito:citesAsAuthority as other relevant material may be used.

**Comment by AlasdairGray** [comment]
Do you have a particular example use case in mind where you want ```dct:references``` instead of ```cito:citesAsAuthority```? 
The consequence here is that we would be weakening the semantic interpretation of the predicate.

**Comment by AlasdairGray** [comment]
Add ```dct:references``` as an additional property and update the guidance notes so that ```cito:citesAsAuthority``` is only used for its specific semantics
