### ISSUE TITLE
Separate out Linksets

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#116]
Section 6.6.2.7 gives details of Linksets as part of the enhanced statistics. Since these make linked datasets 5* should we be promoting this to its own section, Section 6.7, and treating them as datasets in their own right?

**Comment by micheldumontier** [comment]
sure.  there is linkset data in chembl?

**Comment by AlasdairGray** [comment]
Yes, they publish links to UniProt.

But my argument is that Linksets are a part of the dataset that should be properly described, not merely a statistic to be reported. I would also raise these to a SHOULD since they are what make your data 5* linked data. A supporting use case for this comes from Open PHACTS,

**Comment by AlasdairGray** [comment]
You can find a draft of the linkset section at http://htmlpreview.github.io/?https://github.com/joejimbo/HCLSDatasetDescriptions/blob/Linksets/Overview.html#linksets which corresponds to commit
https://github.com/indiedotkim/HCLSDatasetDescriptions/commit/3988fdda1e7fcf64c2e20ad527442e3aa8fbff47
Note that I have not updated the table, nor the table of contents or example.

**Comment by AlasdairGray** [comment]
I will merge in the branch once I've moved it into section 6.5 and added the note about VoID subset usage

**Comment by AlasdairGray** [comment]
Fixed with commit 0799bc5
