### ISSUE TITLE
Creator and date rules

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#118]
When adding the description column, we have changed the requirements for what properties must be provided and may be provided for declaring authorship and dates associated with a dataset. Is this intentional?
Previously pav terms were may and dct terms were must.

**Comment by AlasdairGray** [comment]
This has affects for the validation of documents

**Comment by AlasdairGray** [comment]
Same applies to Source Provenance

**Comment by micheldumontier** [comment]
I don't believe that source provenance was a must.

**Comment by AlasdairGray** [comment]
No, but I believe some were should and some were may, although I have not verified.
There is also a consequence of presenting them this way from a validation point of view. By reading the logical or it is assumed that if one of them is present then the category is satisfied.

**Comment by mscottm** [comment]
Is the question whether to require at least dct and allow pav terms vs allow either or both dct and pav terms in the validator?
