### ISSUE TITLE
Possible typos?

### ISSUE THREAD

**Issue by yayamamo** [indiedotkim/HCLSDatasetDescriptions#120]
Hi,

Since I'm a non-native English speaker, I'm not sure, but the followings seem to be typos.

6 Metadata Guidance Notes
Thus, to be fully conformant with this specification,
->
Thus, to be fully conformance with this specification, 

6.2.4 Dates of Creation and Issuance
which states the orginal creation date of the dataset.
->
which states the original creation date of the dataset.

6.2.6 Publisher
viz the person, organisation, or service
->
viz. the person, organisation, or service

7.1 Workflows
This section will briefly describe the contex of how a dataset might be consumed or produced within a workflow definition.
->
This section will briefly describe the context of how a dataset might be consumed or produced within a workflow definition.

In addition, only the section 9 may be written in US English.
Below are the lists I found.
standardized / summarized / analyzing / analyze / visualization / categorization / modelling / harmonized / harmonization / normalize / catalog

Please discard if these are unimportant.

**Comment by micheldumontier** [comment]
Thanks!
 fixed the typos. we'll keep the US spelling.
