### ISSUE TITLE
Running example must conform to property table

### ISSUE THREAD

**Issue by AlasdairGray** [indiedotkim/HCLSDatasetDescriptions#42]
We need to ensure that the running example conforms with the declarations in the property table. 

For example, I have just discovered that the running example uses the summary level for the preferred prefix, but this is a property that can only be associated with a distribution.

For validation it would be best to start with the complete example and then copy and paste the relevant parts to each of the sections.

**Comment by micheldumontier** [comment]
@AlasdairGray to do everything except statistics section, until this is finalized.

**Comment by micheldumontier** [comment]
statistics section is finished now.

**Comment by AlasdairGray** [comment]
I have updated the running example and the guidance notes for the whole document except for the enhanced statistics. You can find the most recent commit https://github.com/indiedotkim/HCLSDatasetDescriptions/commit/6aabb49fccb23989cb60035c727734835a32ef6c

This can be previewed at
http://htmlpreview.github.io/?https://github.com/joejimbo/HCLSDatasetDescriptions/blob/WorkingExample/Overview.html

@micheldumontier can you update the enhanced statistics section as per the basic statistics; also the example file and the appendix.

We'll then need to merge back with the master and this issue can be closed.

**Comment by micheldumontier** [comment]
These can be really quite large. perhaps we should omit the enhanced statistics from the example? or should i just include an exemplar for each type?

**Comment by micheldumontier** [comment]
ok, i filled out the examples and committed the the changes. 23ad61bf72dae807dca438da7583431897feab11

**Comment by AlasdairGray** [comment]
Thanks @micheldumontier. I've merge the branch back into the master 7614b604fae10aeee6fb51abd327b7ffe5c6880d
